Fix import error from settings
The __init__ module of this xblock should not contain any code because
it is loaded by the LMS/CMS settings; importing triggers a chain of
imports that fails because of yet-undefined settings. E.g:

    AttributeError: 'Settings' object has no attribute
    'COURSE_ID_PATTERN'